## These variables will be overriden in main.py

MIN_CONTRACT_AGE_DAYS = None
TOP_SYMBOLS_BY_VOLUME = None
ADDITIONAL_SYMBOLS = None
EXCLUDED_SYMBOLS = None
KNOWN_SYMBOLS_DB_PATH = None
DB_PATH = None

SYMBOL_CONFIGS = None
DEFAULT_TRAILING_STEP_MULTIPLIER = None
DEFAULT_TRAILING_COUNT = None

MIN_PRICE_INCREMENTS = None
positions = {}
DEBUG_MODE = None
