## These variables will be overriden in main.py

MIN_CONTRACT_AGE_DAYS = None
TOP_SYMBOLS_BY_VOLUME = None
ADDITIONAL_SYMBOLS = None
EXCLUDED_SYMBOLS = None
KNOWN_SYMBOLS_DB_PATH = None
DB_PATH = None

SYMBOL_CONFIGS = None
DEFAULT_TRAILING_STEP_MULTIPLIER = None
DEFAULT_TRAILING_COUNT = None

MIN_PRICE_INCREMENTS = None
positions = {}
DEBUG_MODE = None
TRAILING_STOPS_MAP = None
LAST_AVAILABLE_BALANCE = None
TRENDRANGE_CACHE_TIMEOUT = None

CONTRACTS_MAP = None
CONTRACT_SIZES = None

TRADE_MAX_CANDLES = None
CANDLE_INTERVAL_MINUTES = None
VOL_BOTTOM_PERCENTILE = None
VOL_TOP_PERCENTILE = None
REOPEN_ON_WIN = None
REOPEN_ON_BREAKEVEN = None
RANGE_ENTRY_OFFSET_PCT = None
RANGE_TAKE_PROFIT_PCT = None
RANGE_STOP_LOSS_PCT = None

API_DELAY_MS = None
ATR_MA_PERIOD = None
CLIENT_NAME = None
check_sleep_start = None

TREND_STOP_LOSSES = None
TREND_TAKE_PROFITS = None
TRAILING_TRIGGER_PRICES = None
TRAILING_LENGTHS = None
MINIMUM_TRAILING_LENGTHS = None
TREND_SCORES_TMP = None
fib_level = None
