## These variables will be overriden in main.py

MIN_CONTRACT_AGE_DAYS = None
TOP_SYMBOLS_BY_VOLUME = None
ADDITIONAL_SYMBOLS = None
EXCLUDED_SYMBOLS = None
KNOWN_SYMBOLS_DB_PATH = None
DB_PATH = None

SYMBOL_CONFIGS = None
DEFAULT_TRAILING_STEP_MULTIPLIER = None
DEFAULT_TRAILING_COUNT = None

MIN_PRICE_INCREMENTS = None
positions = {}
DEBUG_MODE = None
TRAILING_STOPS_MAP = None
LAST_AVAILABLE_BALANCE = None
TRENDRANGE_CACHE_TIMEOUT = None

CONTRACTS_MAP = None
CONTRACT_SIZES = None

TRADE_MAX_CANDLES = None
